version: '3'
services:
  spot_simulation:
    image: spot_simulation
    build: .
      #volumes:
      #  - "${PWD}/src:/catkin_ws/src"
    network_mode: host
    privileged: true
      #devices:
      # - /dev:/dev
        #- /dev/ttyUSB0:/dev/ttyUSB0
    command: /bin/bash -c "/setup.bash"
        #command: /bin/bash -c "tail -f /dev/null"

